name: Update
description: Request a completer update
title: "<command> update <version>"
labels: [enhancement, completer, fund]
body:
- type: input
  attributes:
    label: Command
    description: Name of the command (as typed on the command line).
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: Version number of the release.
  validations:
    required: true
- type: input
  attributes:
    label: Release
    description: Link to the release.
  validations:
    required: true
- type: input
  attributes:
    label: Changelog
    description: Changelog of the release (if available).
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the request!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
